# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: BuildAndRun
  pool:
    vmImage: ubuntu-latest

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      javac hello.java
      java hello
    displayName: 'Compile and Run Java Program'
